### ISSUE TITLE
Do not abort on additional SYSTEMSERVERCLASSPATH

### ISSUE THREAD

**Issue by arter97** [rovo89/android_art#14]
It'll be not a major fix, but I'll still appreciate it if you apply it.

http://forum.xda-developers.com/android/development/fixing-boot-custom-kernels-support-t3170606
Patch is attached.

**Comment by rovo89** [comment]
If I understand the problem correctly, CM requires an additional file in the SYSTEMSERVERCLASSPATH, which doesn't exist on other ROMs, so you have a problem when you want to build a kernel that works for both. Right?

Hm, I'm not so convinced of your patch. Some issues I have with it:
- It disables the file existence check for **all** apps, not just for the system server.
- It disables the logging, which would be useful for diagnostics.
- The result is undefined, as the code after the early exit assumes that the file exists.
- The further processing is even more undefined, as you have to hope the Android does the right things with the "random" return value of the function.

From my point of view, better solutions would be:
1. Only add the additional file to SYSTEMSERVERCLASSPATH if it exists or if a certain ROM is detected.
2. Limit your patch to the SYSTEMSERVERCLASSPATH, e.g. by checking the package (if possible) and whether getenv("SYSTEMSERVERCLASSPATH") contains the file. Also keep logging that the file wasn't found and return that no dexopt is needed.
3. Adjust the SYSTEMSERVERCLASSPATH dynamically.

I would definitely prefer option 1, if somehow possible. Not sure if conditions are supported in init.rc, but maybe there's a similar way.

Otherwise, option 3 might be possible. Not sure about the best place, but maybe when the runtime is created, it could check SYSTEMSERVERCLASSPATH and remove any non-existent files from the environment variable. Or maybe in app_process, and only when the Zygote for the system_server is started? Obviously, it would still have to log what it did.

**Comment by rovo89** [comment]
Any progress here? Is this still needed or can it be closed?

**Comment by arter97** [comment]
Nah, just close it.
This is a rare case and I don't think it's worth it to "code" for a better
fix.
